### PR TITLE
General Website Improvements and Content Restoration

### PR DESCRIPTION
**Pull request by ProjectSynchro**
Done:
- [x] Automatic copyright date
- [x] Author for blarg posts
- [x] Re-added macOS links to download page and updated descriptions
- [x] Tags for blarg posts (currently unused)
- [x] Function-thingies for image and video figures.
- [x] Ported content from archived blog.naev.org
- [x] Restored old images from archive.org

### CODE REVIEW

**Comment by ProjectSynchro** [comment]
TODO
Re-do index page so we don't load all of the blarg posts.

**Comment by bobbens** [comment]
nostalgia++

**Comment by ProjectSynchro** [comment]
> 
> 
> nostalgia++

I'm surprised I got through the one explaining physics without my brain exploding 😅

**Comment by ProjectSynchro** [comment]
All older content that was archived has been ported into markdown and added to this PR, some images were lost to time, and others are just a preview thumbnail due to no alternatives being found.

**Comment by bobbens** [comment]
We should also make a blarg post when this is done so people know we got it working :)

**Comment by ProjectSynchro** [comment]
Will be merged with upcoming.

**Comment by ProjectSynchro** [comment]
Going to reopen this so I don't forget about it 😅

**Comment by ProjectSynchro** [comment]
Kinda merged this stuff into upcoming
Closing.

**Pull request closed without merging**
